from aiogram import Bot, types
from aiogram.types import InlineKeyboardMarkup, InlineKeyboardButton

start = types.ReplyKeyboardMarkup(resize_keyboard=True)

help_bot = types.KeyboardButton('Help')

add_bike_2 = types.KeyboardButton('Страница 2')
add_bike_3 = types.KeyboardButton('Страница 3')
add_bike_4 = types.KeyboardButton('Страница 4')
add_bike_5 = types.KeyboardButton('Страница 5')
add_bike_6 = types.KeyboardButton('Страница 6')
add_bike_7 = types.KeyboardButton('Страница 7')
add_bike_8 = types.KeyboardButton('Страница 8')
add_bike_9 = types.KeyboardButton('Страница 9')
add_bike_10 = types.KeyboardButton('Страница 10')

return_to_page_1 = types.KeyboardButton('Вернутся к странице 1')
return_to_page_2 = types.KeyboardButton('Вернутся к странице 2')
return_to_page_3 = types.KeyboardButton('Вернутся к странице 3')
return_to_page_4 = types.KeyboardButton('Вернутся к странице 4')
return_to_page_5 = types.KeyboardButton('Вернутся к странице 5')
return_to_page_6 = types.KeyboardButton('Вернутся к странице 6')
return_to_page_7 = types.KeyboardButton('Вернутся к странице 7')
return_to_page_8 = types.KeyboardButton('Вернутся к странице 8')
return_to_page_9 = types.KeyboardButton('Вернутся к странице 9')

bike_Apollo = types.KeyboardButton('Apollo')
bike_Aprilia = types.KeyboardButton('Aprilia')
bike_Avantis = types.KeyboardButton('Avantis')
bike_BAJAJ = types.KeyboardButton('BAJAJ')
bike_Baltmotors = types.KeyboardButton('Baltmotors')
bike_Benelli = types.KeyboardButton('Benelli')
bike_Beta = types.KeyboardButton('Beta')
bike_BMW = types.KeyboardButton('BMW')
bike_Briar = types.KeyboardButton('Briar')
bike_BRP = types.KeyboardButton('BRP')
start.add(bike_Apollo, bike_Aprilia, bike_Avantis, bike_BAJAJ, bike_Baltmotors, bike_Benelli, bike_Beta, bike_BMW,
          bike_Briar, bike_BRP, add_bike_2)

motorcycles_add_1 = types.ReplyKeyboardMarkup()
bike_BRZ = types.KeyboardButton('BRZ')
bike_BSE = types.KeyboardButton('BSE')
bike_Buell = types.KeyboardButton('Buell')
bike_Cagiva = types.KeyboardButton('Cagiva')
bike_Cezet = types.KeyboardButton('Cezet')
bike_Daelim = types.KeyboardButton('Daelim')
bike_Ducati = types.KeyboardButton('Ducati')
bike_Ekonika_Roliz = types.KeyboardButton('Ekonika Roliz')
bike_Fuego = types.KeyboardButton('Fuego')
motorcycles_add_1.add(bike_BRZ, bike_BSE, bike_Buell, bike_Cagiva, bike_Cezet, bike_Daelim, bike_Ducati,
                      bike_Ekonika_Roliz, bike_Fuego, return_to_page_1, add_bike_3)

motorcycles_add_2 = types.ReplyKeyboardMarkup()
bike_Gas_Gas = types.KeyboardButton('Gas Gas')
bike_Gilera = types.KeyboardButton('Gilera')
bike_GR = types.KeyboardButton('GR')
bike_Guowei = types.KeyboardButton('Guowei')
bike_Harley_Davidson = types.KeyboardButton('Harley-Davidson')
bike_Honda = types.KeyboardButton('Honda')
bike_Hors = types.KeyboardButton('Hors')
bike_Husqvarna = types.KeyboardButton('Husqvarna')
bike_Hyosung = types.KeyboardButton('Hyosung')
motorcycles_add_2.add(bike_Gas_Gas, bike_Gilera, bike_GR, bike_Guowei, bike_Harley_Davidson, bike_Honda, bike_Hors,
                      bike_Husqvarna, bike_Hyosung, return_to_page_2, add_bike_4)

motorcycles_add_3 = types.ReplyKeyboardMarkup()
bike_Indian = types.KeyboardButton('Indian')
bike_Irbis = types.KeyboardButton('Irbis')
bike_Jaguar = types.KeyboardButton('Jaguar')
bike_Jawa = types.KeyboardButton('Jawa')
bike_JMC = types.KeyboardButton('JMC')
bike_Kangchao = types.KeyboardButton('Kangchao')
bike_Kawasaki = types.KeyboardButton('Kawasaki')
bike_Kayo = types.KeyboardButton('Kayo')
bike_Keeway = types.KeyboardButton('Keeway')
bike_Kinroad = types.KeyboardButton('Kinroad')
motorcycles_add_3.add(bike_Indian, bike_Irbis, bike_Jaguar, bike_Jawa, bike_JMC, bike_Kangchao, bike_Kawasaki,
                      bike_Kayo, bike_Keeway, bike_Kinroad, return_to_page_3, add_bike_5)

motorcycles_add_4 = types.ReplyKeyboardMarkup()
bike_Koshine = types.KeyboardButton('Koshine')
bike_KTM = types.KeyboardButton('KTM')
bike_KXD = types.KeyboardButton('KXD')
bike_Kymco = types.KeyboardButton('Kymco')
bike_Lifan = types.KeyboardButton('Lifan')
bike_Linhai = types.KeyboardButton('Linhai')
bike_Loncin = types.KeyboardButton('Loncin')
bike_Megelli = types.KeyboardButton('Megelli')
bike_Motax = types.KeyboardButton('Motax')
motorcycles_add_4.add(bike_Koshine, bike_KTM, bike_KXD, bike_Kymco, bike_Lifan, bike_Linhai, bike_Loncin, bike_Megelli,
                      bike_Motax, return_to_page_4, add_bike_6)

motorcycles_add_5 = types.ReplyKeyboardMarkup()
bike_Moto_Guzzi = types.KeyboardButton('Moto Guzzi')
bike_Motoland = types.KeyboardButton('Motoland')
bike_MV_Agusta = types.KeyboardButton('MV Agusta')
bike_MZ = types.KeyboardButton('MZ')
bike_Nexus = types.KeyboardButton('Nexus')
bike_Nitro = types.KeyboardButton('Nitro')
bike_Pannonia = types.KeyboardButton('Pannonia')
bike_PitsterPro = types.KeyboardButton('PitsterPro')
bike_Polini = types.KeyboardButton('Polini')
motorcycles_add_5.add(bike_Moto_Guzzi, bike_Motoland, bike_MV_Agusta, bike_MZ, bike_Nexus, bike_Nitro, bike_Pannonia,
                      bike_PitsterPro, bike_Polini, return_to_page_5, add_bike_7)

motorcycles_add_6 = types.ReplyKeyboardMarkup()
bike_Qingqi = types.KeyboardButton('Qingqi')
bike_Racer = types.KeyboardButton('Racer')
bike_Reggy = types.KeyboardButton('Reggy')
bike_Regulmoto = types.KeyboardButton('Regulmoto')
bike_Rieju = types.KeyboardButton('Rieju')
bike_Royal_Enfield = types.KeyboardButton('Royal Enfield')
bike_Sherco = types.KeyboardButton('Sherco')
bike_Skyline = types.KeyboardButton('Skyline')
bike_Stels = types.KeyboardButton('Stels')
motorcycles_add_6.add(bike_Qingqi, bike_Racer, bike_Reggy, bike_Regulmoto, bike_Rieju, bike_Royal_Enfield, bike_Sherco,
                      bike_Skyline, bike_Stels, return_to_page_6, add_bike_8)

motorcycles_add_7 = types.ReplyKeyboardMarkup()
bike_Super_Soco = types.KeyboardButton('Super Soco')
bike_Suzuki = types.KeyboardButton('Suzuki')
bike_SWM = types.KeyboardButton('SWM')
bike_TM_Racing = types.KeyboardButton('TM Racing')
bike_Triumph = types.KeyboardButton('Triumph')
bike_Vento = types.KeyboardButton('Vento')
bike_Victory = types.KeyboardButton('Victory')
bike_Viper = types.KeyboardButton('Viper')
bike_Virus = types.KeyboardButton('Virus')
motorcycles_add_7.add(bike_Super_Soco, bike_Suzuki, bike_SWM, bike_TM_Racing, bike_Triumph, bike_Vento, bike_Victory,
                      bike_Viper, bike_Virus, return_to_page_7, add_bike_9)

motorcycles_add_8 = types.ReplyKeyboardMarkup()
bike_VOGE = types.KeyboardButton('VOGE')
bike_Wels = types.KeyboardButton('Wels')
bike_Xmotos = types.KeyboardButton('Xmotos')
bike_Yamaha = types.KeyboardButton('Yamaha')
bike_YCF = types.KeyboardButton('YCF')
bike_Zipp = types.KeyboardButton('Zipp')
bike_Zongshen = types.KeyboardButton('Zongshen')
bike_Zuum = types.KeyboardButton('Zuum')
bike_avm = types.KeyboardButton('АВМ')
motorcycles_add_8.add(bike_VOGE, bike_Wels, bike_Xmotos, bike_Yamaha, bike_YCF, bike_Zipp, bike_Zongshen, bike_Zuum,
                      bike_avm, return_to_page_8, add_bike_10)

motorcycles_add_9 = types.ReplyKeyboardMarkup()
bike_alfamoto = types.KeyboardButton('Альфамото')
bike_voshod = types.KeyboardButton('Восход')
bike_dnepr = types.KeyboardButton('Днепр')
bike_zid = types.KeyboardButton('ЗиД')
bike_izh = types.KeyboardButton('ИЖ')
bike_minsk = types.KeyboardButton('Минск')
bike_ural = types.KeyboardButton('Урал')
bike_eksklyuziv = types.KeyboardButton('Эксклюзив')
motorcycles_add_9.add(bike_alfamoto, bike_voshod, bike_dnepr, bike_zid, bike_izh, bike_minsk, bike_ural,
                      bike_eksklyuziv, return_to_page_9)


return_keyb = InlineKeyboardMarkup()
return_keyb.add(InlineKeyboardButton(f'Return', callback_data='cancel'))
